CREATE TABLE IF NOT EXISTS USERS(
	USERNAME_ID			int NOT NULL PRIMARY KEY AUTO_INCREMENT,
 	EMAIL				NVARCHAR(30),
    USERNAME			NVARCHAR (30)  NOT NULL UNIQUE,
	USER_PASSWORD		NVARCHAR (30)  NOT NULL,
	
	FULL_NAME			NVARCHAR (30),
	LAST_NAME			NVARCHAR (30) 

);


DELIMITER $$
CREATE PROCEDURE RegisterUser(vNAME varchar(200) , vLASTNAME varchar(200), vEMAIL varchar(200), vUSER varchar(200), vPASS varchar(200))
BEGIN
    INSERT INTO USERS (FULL_NAME,LAST_NAME,EMAIL,USERNAME,USER_PASSWORD) VALUES(vNAME,vLASTNAME,vEMAIL,vUSER,vPASS); 
END$$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE LogInUser(vEMAIL varchar(200), vPASS varchar(200))
BEGIN
    SELECT * FROM USERS WHERE EMAIL = vEMAIL AND USER_PASSWORD = vPassword;
END$$
DELIMITER ;